[package]
name = "tmp"
version = "0.1.0"
edition = "2021"
description = "Tui Music Player"

[dependencies]
audiotags = "0.5.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
rodio = "0.20.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
